---
deployment:
  tasks:
    - cd /home/batlamed/batla-medicos && git checkout -- . && git clean -fd
    - export PATH=/home/batlamed/nodevenv/batla-medicos/24/bin:$PATH && cd /home/batlamed/batla-medicos/backend && npm install --production
    - export PATH=/home/batlamed/nodevenv/batla-medicos/24/bin:$PATH && cd /home/batlamed/batla-medicos/frontend && rm -rf dist && npm install && npm run build
    - mkdir -p /home/batlamed/batla-medicos/tmp && touch /home/batlamed/batla-medicos/tmp/restart.txt
