---
deployment:
  tasks:
    - export PATH=/opt/alt/alt-nodejs22/root/usr/bin:/home/batlamed/nodevenv/batla-medicos/22/bin:$PATH && cd /home/batlamed/batla-medicos/backend && npm install --production
    - mkdir -p /home/batlamed/batla-medicos/tmp && touch /home/batlamed/batla-medicos/tmp/restart.txt
